baseURL = 'https://gregsarjeant.net/'
languageCode = 'en-us'
title = 'Greg Sarjeant'
theme = "ananke"
SectionPagesMenu = "main"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Greg's place"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  disable_share = true

  [params.ananke]
    featured_image = "/images/fall_farm.jpeg"
  [params.ananke_socials]
    [params.ananke_socials.linkedin]
      name = "linkedin"
      url = "https://linkedin.com/in/gregsarjeant"
    [params.ananke_socials.github]
      name = "github"
      url = "https://github.com/gsarjeant"